services:
  practice-work-sso:
    build:
      context: .
    environment:
      NODE_ENV: production
      # Your application's Client ID provided by the Identity Provider
      CLIENT_ID: TODO-add-client-id-here
      # Your application's Client Secret provided by the Identity Provider
      CLIENT_SECRET: TODO-add-client-secret-here
      # Redirect URI registered with the Identity Provider
      # It must match exactly, e.g., "http://localhost:3000/callback"
      REDIRECT_URI: http://localhost:3000/callback
    ports:
      - 3000:3000
    restart: unless-stopped
